package lionsclub.com.directoryapp;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import lionsclub.com.directoryapp.District;
import lionsclub.com.directoryapp.Club;
import lionsclub.com.directoryapp.Member;
import lionsclub.com.directoryapp.CredentialRequestQueue;

import lionsclub.com.directoryapp.DistrictDao;
import lionsclub.com.directoryapp.ClubDao;
import lionsclub.com.directoryapp.MemberDao;
import lionsclub.com.directoryapp.CredentialRequestQueueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig districtDaoConfig;
    private final DaoConfig clubDaoConfig;
    private final DaoConfig memberDaoConfig;
    private final DaoConfig credentialRequestQueueDaoConfig;

    private final DistrictDao districtDao;
    private final ClubDao clubDao;
    private final MemberDao memberDao;
    private final CredentialRequestQueueDao credentialRequestQueueDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        districtDaoConfig = daoConfigMap.get(DistrictDao.class).clone();
        districtDaoConfig.initIdentityScope(type);

        clubDaoConfig = daoConfigMap.get(ClubDao.class).clone();
        clubDaoConfig.initIdentityScope(type);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        credentialRequestQueueDaoConfig = daoConfigMap.get(CredentialRequestQueueDao.class).clone();
        credentialRequestQueueDaoConfig.initIdentityScope(type);

        districtDao = new DistrictDao(districtDaoConfig, this);
        clubDao = new ClubDao(clubDaoConfig, this);
        memberDao = new MemberDao(memberDaoConfig, this);
        credentialRequestQueueDao = new CredentialRequestQueueDao(credentialRequestQueueDaoConfig, this);

        registerDao(District.class, districtDao);
        registerDao(Club.class, clubDao);
        registerDao(Member.class, memberDao);
        registerDao(CredentialRequestQueue.class, credentialRequestQueueDao);
    }
    
    public void clear() {
        districtDaoConfig.getIdentityScope().clear();
        clubDaoConfig.getIdentityScope().clear();
        memberDaoConfig.getIdentityScope().clear();
        credentialRequestQueueDaoConfig.getIdentityScope().clear();
    }

    public DistrictDao getDistrictDao() {
        return districtDao;
    }

    public ClubDao getClubDao() {
        return clubDao;
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

    public CredentialRequestQueueDao getCredentialRequestQueueDao() {
        return credentialRequestQueueDao;
    }

}
