package lionsclub.com.directoryapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEMBER.
 */
public class Member {

    private Long id;
    private String name;
    private String profileImage;
    private Boolean online;
    private String distId;
    private String email;
    private String mobile;
    private Boolean canEdit;
    private Long mIntNum;
    private String profession;
    private String spouse;
    private String aboutMe;
    private String joinDate;
    private String city;
    private String phone;
    private String altPhone;
    private String altMobile;
    private String altEmail;
    private String residentialAddress;
    private String businessAddress;
    private String dob;
    private String marriageDate;
    private String profilePicUrl;
    private String userName;
    private String password;
    private String clubName;
    private String district;
    private Boolean isProfileDownloaded;
    /**
     * Not-null value.
     */
    private String clubId;

    public Member() {
    }

    public Member(Long id) {
        this.id = id;
    }

    public Member(Long id, String name, String profileImage, Boolean online, String distId, String email, String mobile, Boolean canEdit, Long mIntNum, String profession, String spouse, String aboutMe, String joinDate, String city, String phone, String altPhone, String altMobile, String altEmail, String residentialAddress, String businessAddress, String dob, String marriageDate, String profilePicUrl, String userName, String password, String clubName, String district, Boolean isProfileDownloaded, String clubId) {
        this.id = id;
        this.name = name;
        this.profileImage = profileImage;
        this.online = online;
        this.distId = distId;
        this.email = email;
        this.mobile = mobile;
        this.canEdit = canEdit;
        this.mIntNum = mIntNum;
        this.profession = profession;
        this.spouse = spouse;
        this.aboutMe = aboutMe;
        this.joinDate = joinDate;
        this.city = city;
        this.phone = phone;
        this.altPhone = altPhone;
        this.altMobile = altMobile;
        this.altEmail = altEmail;
        this.residentialAddress = residentialAddress;
        this.businessAddress = businessAddress;
        this.dob = dob;
        this.marriageDate = marriageDate;
        this.profilePicUrl = profilePicUrl;
        this.userName = userName;
        this.password = password;
        this.clubName = clubName;
        this.district = district;
        this.isProfileDownloaded = isProfileDownloaded;
        this.clubId = clubId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProfileImage() {
        return profileImage;
    }

    public void setProfileImage(String profileImage) {
        this.profileImage = profileImage;
    }

    public Boolean getOnline() {
        return online;
    }

    public void setOnline(Boolean online) {
        this.online = online;
    }

    public String getDistId() {
        return distId;
    }

    public void setDistId(String distId) {
        this.distId = distId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Boolean getCanEdit() {
        return canEdit;
    }

    public void setCanEdit(Boolean canEdit) {
        this.canEdit = canEdit;
    }

    public Long getMIntNum() {
        return mIntNum;
    }

    public void setMIntNum(Long mIntNum) {
        this.mIntNum = mIntNum;
    }

    public String getProfession() {
        return profession;
    }

    public void setProfession(String profession) {
        this.profession = profession;
    }

    public String getSpouse() {
        return spouse;
    }

    public void setSpouse(String spouse) {
        this.spouse = spouse;
    }

    public String getAboutMe() {
        return aboutMe;
    }

    public void setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
    }

    public String getJoinDate() {
        return joinDate;
    }

    public void setJoinDate(String joinDate) {
        this.joinDate = joinDate;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAltPhone() {
        return altPhone;
    }

    public void setAltPhone(String altPhone) {
        this.altPhone = altPhone;
    }

    public String getAltMobile() {
        return altMobile;
    }

    public void setAltMobile(String altMobile) {
        this.altMobile = altMobile;
    }

    public String getAltEmail() {
        return altEmail;
    }

    public void setAltEmail(String altEmail) {
        this.altEmail = altEmail;
    }

    public String getResidentialAddress() {
        return residentialAddress;
    }

    public void setResidentialAddress(String residentialAddress) {
        this.residentialAddress = residentialAddress;
    }

    public String getBusinessAddress() {
        return businessAddress;
    }

    public void setBusinessAddress(String businessAddress) {
        this.businessAddress = businessAddress;
    }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getMarriageDate() {
        return marriageDate;
    }

    public void setMarriageDate(String marriageDate) {
        this.marriageDate = marriageDate;
    }

    public String getProfilePicUrl() {
        return profilePicUrl;
    }

    public void setProfilePicUrl(String profilePicUrl) {
        this.profilePicUrl = profilePicUrl;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getClubName() {
        return clubName;
    }

    public void setClubName(String clubName) {
        this.clubName = clubName;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public Boolean getIsProfileDownloaded() {
        return isProfileDownloaded;
    }

    public void setIsProfileDownloaded(Boolean isProfileDownloaded) {
        this.isProfileDownloaded = isProfileDownloaded;
    }

    /** Not-null value. */
    public String getClubId() {
        return clubId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClubId(String clubId) {
        this.clubId = clubId;
    }

}
