package app.WebService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 5/25/2015 11:24:40 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class BannerInfo implements KvmSerializable {
    
    public String title;
    public String desc;
    public String uRL;
    public String image;
    
    public BannerInfo(){}
    
    public BannerInfo(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Title"))
        {
            Object obj = soapObject.getProperty("Title");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                title = j.toString();
            }else if (obj!= null && obj instanceof String){
                title = (String) obj;
            }
        }
        if (soapObject.hasProperty("Desc"))
        {
            Object obj = soapObject.getProperty("Desc");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                desc = j.toString();
            }else if (obj!= null && obj instanceof String){
                desc = (String) obj;
            }
        }
        if (soapObject.hasProperty("URL"))
        {
            Object obj = soapObject.getProperty("URL");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                uRL = j.toString();
            }else if (obj!= null && obj instanceof String){
                uRL = (String) obj;
            }
        }
        if (soapObject.hasProperty("Image"))
        {
            Object obj = soapObject.getProperty("Image");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                image = j.toString();
            }else if (obj!= null && obj instanceof String){
                image = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return title;
            case 1:
                return desc;
            case 2:
                return uRL;
            case 3:
                return image;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Title";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Desc";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "URL";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Image";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
