package app.WebService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/15/2015 10:32:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class Club implements KvmSerializable {
    
    public String iD;
    public String name;
    public int mems;
    public VectorMember membersIn;

    public Club() {
    }

    public Club(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ID")) {
            Object obj = soapObject.getProperty("ID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                iD = j.toString();
            } else if (obj != null && obj instanceof String) {
                iD = (String) obj;
            }
        }
        if (soapObject.hasProperty("Name")) {
            Object obj = soapObject.getProperty("Name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                name = j.toString();
            } else if (obj != null && obj instanceof String) {
                name = (String) obj;
            }
        }
        if (soapObject.hasProperty("Mems")) {
            Object obj = soapObject.getProperty("Mems");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                mems = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                mems = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("MembersIn")) {
            SoapObject j = (SoapObject) soapObject.getProperty("MembersIn");
            membersIn = new VectorMember(j);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return iD;
            case 1:
                return name;
            case 2:
                return mems;
            case 3:
                return membersIn;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ID";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Name";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "Mems";
                break;
            case 3:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "MembersIn";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
