package app.WebService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/15/2015 10:32:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class CMessage implements KvmSerializable {

    public String message;
    public String dT;
    public String iD;

    public CMessage() {
    }

    public CMessage(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Message")) {
            Object obj = soapObject.getProperty("Message");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                message = j.toString();
            } else if (obj != null && obj instanceof String) {
                message = (String) obj;
            }
        }
        if (soapObject.hasProperty("DT")) {
            Object obj = soapObject.getProperty("DT");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                dT = j.toString();
            } else if (obj != null && obj instanceof String) {
                dT = (String) obj;
            }
        }
        if (soapObject.hasProperty("ID")) {
            Object obj = soapObject.getProperty("ID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                iD = j.toString();
            } else if (obj != null && obj instanceof String) {
                iD = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return message;
            case 1:
                return dT;
            case 2:
                return iD;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Message";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DT";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ID";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
