package app.WebService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/15/2015 10:32:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class CReqMem implements KvmSerializable {

    public String mIntNo;
    public boolean processed;
    public String dT_Requested;
    public String dT_Processed;

    public CReqMem() {
    }

    public CReqMem(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("MIntNo")) {
            Object obj = soapObject.getProperty("MIntNo");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                mIntNo = j.toString();
            } else if (obj != null && obj instanceof String) {
                mIntNo = (String) obj;
            }
        }
        if (soapObject.hasProperty("Processed")) {
            Object obj = soapObject.getProperty("Processed");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                processed = Boolean.parseBoolean(j.toString());
            } else if (obj != null && obj instanceof Boolean) {
                processed = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("DT_Requested")) {
            Object obj = soapObject.getProperty("DT_Requested");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                dT_Requested = j.toString();
            } else if (obj != null && obj instanceof String) {
                dT_Requested = (String) obj;
            }
        }
        if (soapObject.hasProperty("DT_Processed")) {
            Object obj = soapObject.getProperty("DT_Processed");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                dT_Processed = j.toString();
            } else if (obj != null && obj instanceof String) {
                dT_Processed = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return mIntNo;
            case 1:
                return processed;
            case 2:
                return dT_Requested;
            case 3:
                return dT_Processed;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "MIntNo";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "Processed";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DT_Requested";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DT_Processed";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
