package app.WebService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/15/2015 10:32:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Enquiry implements KvmSerializable {

    public String iD;
    public String title;
    public String msg;
    public String dtSent;
    public String by;
    public String byName;

    public Enquiry() {
    }

    public Enquiry(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ID")) {
            Object obj = soapObject.getProperty("ID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                iD = j.toString();
            } else if (obj != null && obj instanceof String) {
                iD = (String) obj;
            }
        }
        if (soapObject.hasProperty("Title")) {
            Object obj = soapObject.getProperty("Title");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                title = j.toString();
            } else if (obj != null && obj instanceof String) {
                title = (String) obj;
            }
        }
        if (soapObject.hasProperty("Msg")) {
            Object obj = soapObject.getProperty("Msg");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                msg = j.toString();
            } else if (obj != null && obj instanceof String) {
                msg = (String) obj;
            }
        }
        if (soapObject.hasProperty("dtSent")) {
            Object obj = soapObject.getProperty("dtSent");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                dtSent = j.toString();
            } else if (obj != null && obj instanceof String) {
                dtSent = (String) obj;
            }
        }
        if (soapObject.hasProperty("By")) {
            Object obj = soapObject.getProperty("By");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                by = j.toString();
            } else if (obj != null && obj instanceof String) {
                by = (String) obj;
            }
        }
        if (soapObject.hasProperty("ByName")) {
            Object obj = soapObject.getProperty("ByName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                byName = j.toString();
            } else if (obj != null && obj instanceof String) {
                byName = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return iD;
            case 1:
                return title;
            case 2:
                return msg;
            case 3:
                return dtSent;
            case 4:
                return by;
            case 5:
                return byName;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ID";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Title";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Msg";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "dtSent";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "By";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ByName";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
