package app.WebService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/15/2015 10:32:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class PDEnq implements KvmSerializable {

    public Product p;
    public VectorEnquiry es;

    public PDEnq() {
    }

    public PDEnq(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("p")) {
            SoapObject j = (SoapObject) soapObject.getProperty("p");
            p = new Product(j);
            
        }
        if (soapObject.hasProperty("es")) {
            SoapObject j = (SoapObject) soapObject.getProperty("es");
            es = new VectorEnquiry(j);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return p;
            case 1:
                return es;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = Product.class;
                info.name = "p";
                break;
            case 1:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "es";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
